module.exports = {
    distData: {
        "北京": "11",
        "天津": "12",
        "河北": "13",
        "山西": "14",
        "内蒙古": "15",
        "辽宁": "21",
        "吉林": "22",
        "黑龙江": "23",
        "上海": "31",
        "江苏": "32",
        "浙江": "33",
        "安徽": "34",
        "福建": "35",
        "江西": "36",
        "山东": "37",
        "河南": "41",
        "湖北": "42",
        "湖南": "43",
        "广东": "44",
        "广西": "45",
        "海南": "46",
        "重庆": "50",
        "四川": "51",
        "贵州": "52",
        "云南": "53",
        "西藏": "54",
        "陕西": "61",
        "甘肃": "62",
        "青海": "63",
        "宁夏": "64",
        "新疆": "65",
    },
    titleEN: [
        "id",
        "GSPLicenseValidDate",
        "positionId",
        "company",
        "lxMedisanPurchaseValidDate",
        "sealImpression",
        "medisanPurchaseValidDate",
        "openAccountPermission",
        "billingInformation",
        "editor",
        "receivingEntrusted",
        "recordDate",
        "legalPersonName",
        "registeredCapital",
        "province",
        "businessLicenseValidDate",
        "licenseValidDate",
        "surveySystem",
        "qualityAgreement",
        "purchasePersonName"
    ],
    titleEN_all: [
        "id",
        "GSPLicenseValidDate",
        "positionId",
        "company",
        "lxMedisanPurchaseValidDate",
        "sealImpression",
        "medisanPurchaseValidDate",
        "openAccountPermission",
        "billingInformation",
        "editor",
        "receivingEntrusted",
        "recordDate",
        "nowDate",
        "qualified",
        "checkTrue",
        "legalPersonName",
        "registeredCapital",
        "province",
        "businessLicenseValidDate",
        "licenseValidDate",
        "surveySystem",
        "qualityAgreement",
        "purchasePersonName"
    ],
    titleCH: [
        "GSP证书有效期",
        "位置",
        "公司名称",
        "兰西采购委托有效期",
        "印章印模",
        "哈三联采购委托有效期",
        "开户许可",
        "开票信息",
        "录入人编号",
        "收货委托",
        "整理时间",
        "法人",
        "注册资金",
        "省份",
        "营业执照有效期",
        "许可证有效期",
        "调查体系",
        "质保协议",
        "采购人"
    ],
    titleCH_all: [
        "GSP证书有效期",
        "位置",
        "公司名称",
        "兰西采购委托有效期",
        "印章印模",
        "哈三联采购委托有效期",
        "开户许可",
        "开票信息",
        "录入人编号",
        "收货委托",
        "整理时间",
        "日期",
        "是否合格",
        "条件",
        "法人",
        "注册资金",
        "省份",
        "营业执照有效期",
        "许可证有效期",
        "调查体系",
        "质保协议",
        "采购人"
    ],
    titleENtoCH: {
        "editor": "录入人编号",
        "province": "省份",
        "qualified": "是否合格",
        "company": "公司名称",
        "legalPersonName": "法人",
        "registeredCapital": "注册资金",
        "businessLicenseValidDate": "营业执照有效期",
        "licenseValidDate": "许可证有效期",
        "GSPLicenseValidDate": "GSP证书有效期",
        "purchasePersonName": "采购人",
        "medisanPurchaseValidDate": "哈三联采购委托有效期",
        "lxMedisanPurchaseValidDate": "兰西采购委托有效期",
        "receivingEntrusted": "收货委托",
        "qualityAgreement": "质保协议",
        "openAccountPermission": "开户许可",
        "billingInformation": "开票信息",
        "surveySystem": "调查体系",
        "sealImpression": "印章印模",
        "recordDate": "整理时间",
        "positionId": "位置",
        "nowDate": "日期",
        "checkTrue": "条件"
    },
    titleCHtoEN: {
        "GSP证书有效期": "GSPLicenseValidDate",
        "位置": "positionId",
        "公司名称": "company",
        "兰西采购委托有效期": "lxMedisanPurchaseValidDate",
        "印章印模": "sealImpression",
        "哈三联采购委托有效期": "medisanPurchaseValidDate",
        "开户许可": "openAccountPermission",
        "开票信息": "billingInformation",
        "录入人编号": "editor",
        "收货委托": "receivingEntrusted",
        "整理时间": "recordDate",
        "日期": "nowDate",
        "是否合格": "qualified",
        "条件": "checkTrue",
        "法人": "legalPersonName",
        "注册资金": "registeredCapital",
        "省份": "province",
        "营业执照有效期": "businessLicenseValidDate",
        "许可证有效期": "licenseValidDate",
        "调查体系": "surveySystem",
        "质保协议": "qualityAgreement",
        "采购人": "purchasePersonName"
    }
}